apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- backend/service.yml
- frontend/deploy.yml
- frontend/service.yml



images:
- name: 743207691822.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
  newName: 743207691822.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
  newTag: 3540910ba0558c32b3b09fd8d979dda6b168659c
- name: 743207691822.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
  newName: 743207691822.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
  newTag: v1.0
